In [4]:
from glob import glob
import pandas as pd

In [8]:
stock_files = sorted(glob('/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC*.csv'))
stock_files

['/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201801-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201802-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201803-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201804-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201805-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201806-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201807-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201808-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201809-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201810-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201811-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201812-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201901-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201902-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201903-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201904-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201905-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201906-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201907-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201908-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201909-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201910-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201911-citibike-tripdata.csv',
 '/users/steven.w/downloads/JC-ShareBiking_data_NY_Jan2018-Dec2019/JC-201912-citibike-tripdata.csv']

In [9]:
df = pd.concat((pd.read_csv(file) for file in stock_files), ignore_index=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 758839 entries, 0 to 758838
Data columns (total 15 columns):
tripduration               758839 non-null int64
starttime                  758839 non-null object
stoptime                   758839 non-null object
start station id           758839 non-null int64
start station name         758839 non-null object
start station latitude     758839 non-null float64
start station longitude    758839 non-null float64
end station id             758839 non-null int64
end station name           758839 non-null object
end station latitude       758839 non-null float64
end station longitude      758839 non-null float64
bikeid                     758839 non-null int64
usertype                   758839 non-null object
birth year                 758839 non-null int64
gender                     758839 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 86.8+ MB

In [11]:
df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [13]:
df.loc[-5:,:]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
758834,283,2019-12-31 23:12:18.5480,2019-12-31 23:17:01.8740,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,29245,Customer,1990,1
758835,267,2019-12-31 23:19:03.5840,2019-12-31 23:23:30.6640,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26153,Subscriber,1989,1
758836,379,2019-12-31 23:19:06.5830,2019-12-31 23:25:25.7970,3209,Brunswick St,40.724176,-74.050656,3185,City Hall,40.717733,-74.043845,26276,Subscriber,1984,1
758837,188,2019-12-31 23:24:00.2630,2019-12-31 23:27:09.0400,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,29461,Subscriber,1987,1
758838,326,2019-12-31 23:45:20.9780,2019-12-31 23:50:47.7490,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29123,Subscriber,1988,1

In [14]:
df.to_csv('share_biking_NY_Jan2018-Dec2019.csv')